server:
  port: 8001
spring:
  application:
    name: eureka
  security:
    user:
      name: xiaoZhao
      password: 123456
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8005/eureka
  server:
    eviction-interval-timer-in-ms: 2000
    enable-self-preservation: false
